services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: backend

    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

    env_file:
      - ./.env
      - ./backend/.env.${ENVIRONMENT}

    volumes:
      - ./backend:/app

    command: npm run start:dev

    networks:
      - autosnl-network

    restart: always

    stop_grace_period: 30s

    depends_on:
      - mongo

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
